# Generated by Django 3.2.7 on 2021-10-12 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping',
            field=models.CharField(choices=[('delivery', 'پیک'), ('tipax', 'تیپاکس'), ('porterage', 'باربری')], default='delivery', max_length=10, null=True),
        ),
    ]
