# Generated by Django 3.2.7 on 2021-11-06 08:09

from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brands',
            options={'verbose_name': 'برند', 'verbose_name_plural': 'برندها'},
        ),
        migrations.AlterModelOptions(
            name='cat_attr',
            options={'verbose_name': 'ویژگی دسته ', 'verbose_name_plural': 'جزییات دسته'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AlterModelOptions(
            name='imageproduct',
            options={'verbose_name': 'تصویر محصول', 'verbose_name_plural': 'تصاویر محصولات'},
        ),
        migrations.AlterModelOptions(
            name='product_attr',
            options={'verbose_name': ' جزییات محصول', 'verbose_name_plural': 'جزییات محصولات'},
        ),
        migrations.AlterModelOptions(
            name='productbase',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterField(
            model_name='brands',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام برند'),
        ),
        migrations.AlterField(
            model_name='cat_attr',
            name='attr_name',
            field=models.CharField(max_length=255, verbose_name='نام ویژگی'),
        ),
        migrations.AlterField(
            model_name='cat_attr',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_cat', to='product.category', verbose_name='از مجموعه'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='imageproduct',
            name='default',
            field=models.BooleanField(default=False, verbose_name='عکس پیش فرض'),
        ),
        migrations.AlterField(
            model_name='imageproduct',
            name='image',
            field=models.ImageField(upload_to=product.models.model_image_directory_path, verbose_name='تصویر محصول'),
        ),
        migrations.AlterField(
            model_name='imageproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='img', to='product.productbase', verbose_name='نام محصول'),
        ),
        migrations.AlterField(
            model_name='product_attr',
            name='attr',
            field=models.CharField(max_length=255, verbose_name='ویژگی'),
        ),
        migrations.AlterField(
            model_name='product_attr',
            name='cat_attr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.cat_attr', verbose_name='ویژگی دسته'),
        ),
        migrations.AlterField(
            model_name='product_attr',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attrs', to='product.productbase', verbose_name='نام محصول'),
        ),
        migrations.AlterField(
            model_name='productbase',
            name='added_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریج ایجاد'),
        ),
        migrations.AlterField(
            model_name='productbase',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='product.brands', verbose_name='برند'),
        ),
        migrations.AlterField(
            model_name='productbase',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='product.category', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='productbase',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='productbase',
            name='name',
            field=models.CharField(max_length=255, verbose_name='نام محصول'),
        ),
        migrations.AlterField(
            model_name='productbase',
            name='previous_price',
            field=models.FloatField(default=0.0, verbose_name='قیمت قبلی'),
        ),
        migrations.AlterField(
            model_name='productbase',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='productbase',
            name='qty',
            field=models.IntegerField(default=1, verbose_name='موجودی'),
        ),
        migrations.AlterField(
            model_name='productbase',
            name='rate',
            field=models.IntegerField(default=3, verbose_name='امتیاز محصول'),
        ),
        migrations.AlterField(
            model_name='productbase',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='نشانی'),
        ),
    ]
